name: shashaCloud
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:

    sdk: flutter
  dartz: ^0.10.1
  dio: ^5.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^8.0.0
  go_router: ^14.2.7
  url_strategy: ^0.3.0

  logger:
  gap: ^3.0.1
  icons_plus: ^5.0.0
  awesome_notifications:
  auto_size_text:
  flutter_dotenv:
  cached_network_image_plus:
  jiffy: ^6.3.1
  wolt_modal_sheet: ^0.6.1
  flutter_smart_dialog: ^4.9.7+9
  flutter_screenutil: ^5.9.3
  easy_localization: ^3.0.7
  flutter_bloc: ^8.1.6
  flutter_carousel_widget: ^3.0.1
  bloc: ^8.1.4
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.2
  firebase_storage: ^12.3.1
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  equatable: ^2.0.5
  lottie:
  encrypt: ^5.0.3
  image_picker: ^1.1.2
  connectivity_plus: ^6.0.5
  awesome_snackbar_content: ^0.1.4
  flutter_cached_manager:
  video_player:
  chewie: ^1.8.5
  wakelock_plus: ^1.2.5
  flutter_swipe_action_cell: ^3.1.4




dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  dependency_validator: ^4.1.0
  hive_generator:



flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/image/icon.png"
  min_sdk_android: 23


flutter:
  uses-material-design: true
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf

  assets:
    - assets/
    - assets/fonts/
    - .env
    - assets/lottie/
    - assets/image/
    - shorebird.yaml
